version: '2.4'

services:

  server:
    build:
      context: ../../
    extends:
      file: ../../${CORERELDIR}infra/compose/base.yml
      service: server

  idilic:
    build:
      context: ../../
    extends:
      file: ../../${CORERELDIR}infra/compose/base.yml
      service: idilic

  database:
    extends:
      file: ../../vendor/seanmorris/ids/infra/compose/base.yml
      service: database

  redis:
    image: redis:5.0
    restart: always

volumes:
  schema:
    driver: local
